# NUMPY CRASH COURSE TASKS

In [1]:
import numpy as np

In [2]:
np.__version__

'2.1.3'

In [3]:
import sys
sys.version

'3.13.5 | packaged by Anaconda, Inc. | (main, Jun 12 2025, 16:37:03) [MSC v.1929 64 bit (AMD64)]'

## creating array
* creating arraay using array()

In [4]:
li=[0,1,2,3,4,5]
li

[0, 1, 2, 3, 4, 5]

In [5]:
arr=np.array(li)
arr

array([0, 1, 2, 3, 4, 5])

In [8]:
type(li),type(arr) # ndarray means n dimenssion array

(list, numpy.ndarray)

## arange()
* Return evenly spaced values within a given interval.

In [9]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [10]:
np.arange(0,7,2)

array([0, 2, 4, 6])

In [11]:
np.arange(-5,5)

array([-5, -4, -3, -2, -1,  0,  1,  2,  3,  4])

In [13]:
np.arange(20,10) # 1st parameter must be smaller than the 2nd parameter

array([], dtype=int64)

## zeros()
* returns zeros as the element of the matrix

In [14]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [16]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [17]:
np.zeros((4,5),dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [19]:
np.zeros([1,20],dtype=int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [20]:
np.zeros([20,20],dtype=int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0,

In [21]:
n=(7,8)
n1=(4,5)
print(np.zeros(n1))

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [22]:
n=(7,8)
n1=(4,5)
print(np.zeros(n,dtype=int))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]


## ones()
* it returns 1 as the element of the matrix

In [23]:
np.ones(12)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [24]:
np.ones(12,dtype=int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [25]:
x=np.ones([3,4],dtype=int)

In [26]:
x

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [28]:
x1=(4,5)
print(np.ones(x1,dtype=int))#hyper prameter tunning

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [29]:
np.twos(3)

AttributeError: module 'numpy' has no attribute 'twos'

## random.rand()
* it returns random values in float

In [30]:
np.rand(1,5)

AttributeError: module 'numpy' has no attribute 'rand'

In [31]:
import random

In [34]:
np.random.rand(1,5)

array([[0.84717228, 0.57949553, 0.8262056 , 0.02940568, 0.56082775]])

In [35]:
np.random.rand(2,5)

array([[0.61495637, 0.98230506, 0.69761811, 0.38128577, 0.25833503],
       [0.54663793, 0.09902834, 0.62499972, 0.31413916, 0.84090295]])

In [38]:
np.random.rand(2,5,4)

array([[[0.13398312, 0.77991965, 0.0371115 , 0.2045586 ],
        [0.84292124, 0.2138099 , 0.52594798, 0.90550006],
        [0.00437016, 0.67291464, 0.66504837, 0.09107986],
        [0.56350705, 0.96214363, 0.27755186, 0.1966194 ],
        [0.73556598, 0.68742808, 0.04795249, 0.75290375]],

       [[0.21672452, 0.89069777, 0.71809461, 0.93415211],
        [0.2358974 , 0.11953094, 0.73687169, 0.80963837],
        [0.60156872, 0.40635489, 0.42507276, 0.68668245],
        [0.81798085, 0.04202184, 0.28037757, 0.69152097],
        [0.03968375, 0.03385464, 0.00966124, 0.98887756]]])

In [39]:
len(np.random.rand(2,5,4))

2

## random.randint()
* it return an random value between give parmeter in int form

In [40]:
np.random.randint(1,4)

2

In [42]:
np.random.randint(0,4,4)


array([2, 3, 1, 3], dtype=int32)

In [44]:
np.random.randint(1,16,(4,4))

array([[ 4,  1, 14, 12],
       [13, 14,  4,  4],
       [12, 10, 10,  9],
       [ 6,  6,  4,  9]], dtype=int32)

In [47]:
np.random.randint(1,7,(10,10))

array([[3, 3, 1, 4, 5, 3, 4, 1, 1, 2],
       [1, 2, 4, 4, 5, 6, 3, 5, 2, 4],
       [2, 1, 1, 4, 4, 3, 5, 1, 3, 6],
       [2, 3, 4, 3, 2, 1, 4, 2, 3, 5],
       [1, 2, 4, 1, 1, 4, 6, 3, 1, 2],
       [6, 4, 1, 1, 6, 5, 5, 2, 1, 6],
       [4, 2, 1, 6, 4, 2, 4, 5, 6, 1],
       [1, 6, 4, 5, 6, 3, 2, 3, 2, 3],
       [1, 5, 5, 5, 6, 2, 1, 2, 6, 2],
       [4, 5, 2, 3, 2, 4, 6, 6, 2, 3]], dtype=int32)

In [48]:
np.random.randint(1,100,(12,12))

array([[98, 49, 51, 59, 67, 81, 75, 49, 59, 92, 70, 70],
       [45, 48, 97, 69, 97, 85, 34, 78, 55, 62, 64, 73],
       [ 5, 65, 62, 83, 88, 71, 90, 91, 87, 21, 14, 70],
       [97, 15, 86, 27, 76, 82,  4, 16, 60, 68, 40, 18],
       [89, 96, 13, 93, 59, 25, 50,  2, 29, 12,  6,  8],
       [15, 44,  9, 25, 12, 30, 21, 36, 53, 44, 92, 52],
       [28, 92, 72, 20, 58,  9, 84, 97, 72, 16, 71, 98],
       [63, 83, 65, 19, 66, 83, 71, 44,  8, 22, 87, 31],
       [55, 36, 64, 41, 82, 98, 46,  4, 85, 64, 43, 88],
       [11, 95, 51, 16, 26, 96, 63,  8, 66, 99, 25, 41],
       [59,  6, 35, 53,  2, 45,  5,  2, 39, 18, 67, 71],
       [95,  3, 33, 68, 97, 62,  6,  3, 71, 58, 31, 39]], dtype=int32)

## reshape()
* it reshaape the shape of the matrix

In [49]:
np.arange(1,21).reshape(4,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [57]:
np.arange(1,55).reshape(9,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36],
       [37, 38, 39, 40, 41, 42],
       [43, 44, 45, 46, 47, 48],
       [49, 50, 51, 52, 53, 54]])

## slicing of the array

In [58]:
r=np.random.randint(1,21,(5,5))

In [59]:
r

array([[ 8,  3, 13, 10,  2],
       [11, 15,  4,  6,  8],
       [ 8, 14, 16, 15, 11],
       [17,  7, 14,  4,  7],
       [14, 15, 16,  8,  4]], dtype=int32)

In [61]:
r[1:3]

array([[11, 15,  4,  6,  8],
       [ 8, 14, 16, 15, 11]], dtype=int32)

In [63]:
r[1,3] # this is how we can find element in a matrix

np.int32(6)

In [64]:
r[0,-1]

np.int32(2)

In [65]:
r

array([[ 8,  3, 13, 10,  2],
       [11, 15,  4,  6,  8],
       [ 8, 14, 16, 15, 11],
       [17,  7, 14,  4,  7],
       [14, 15, 16,  8,  4]], dtype=int32)

In [66]:
r[2:5]

array([[ 8, 14, 16, 15, 11],
       [17,  7, 14,  4,  7],
       [14, 15, 16,  8,  4]], dtype=int32)

In [67]:
r[0:-2]

array([[ 8,  3, 13, 10,  2],
       [11, 15,  4,  6,  8],
       [ 8, 14, 16, 15, 11]], dtype=int32)

In [68]:
r

array([[ 8,  3, 13, 10,  2],
       [11, 15,  4,  6,  8],
       [ 8, 14, 16, 15, 11],
       [17,  7, 14,  4,  7],
       [14, 15, 16,  8,  4]], dtype=int32)

In [69]:
r[-4,-4]

np.int32(15)

In [71]:
r[:]

array([[ 8,  3, 13, 10,  2],
       [11, 15,  4,  6,  8],
       [ 8, 14, 16, 15, 11],
       [17,  7, 14,  4,  7],
       [14, 15, 16,  8,  4]], dtype=int32)

## operations

In [72]:
s=np.random.randint(10,20,10)
s

array([16, 14, 15, 10, 12, 19, 15, 16, 11, 15], dtype=int32)

In [73]:
16 in s

True

In [74]:
17 in s

False

In [75]:
id(s)

1904367287632

In [76]:
arr1=np.random.randint(1,101,(10,10))

In [77]:
arr1

array([[67, 42, 57, 39, 89, 94, 92, 46, 48, 49],
       [71, 43, 36, 89, 92, 30, 75, 14, 77, 70],
       [68, 29, 90, 35, 28, 40, 58, 56, 45, 39],
       [ 1, 15, 63, 81,  9, 72, 96, 37, 86, 21],
       [60,  8, 26, 66, 95, 38, 92, 99, 67, 69],
       [62,  7, 71, 25, 70, 45, 89, 41, 17, 72],
       [52, 53, 51, 11, 16,  6, 56, 73, 89,  6],
       [71, 43, 31, 64, 77, 28, 81, 60, 57, 57],
       [37, 96, 61, 31, 10, 56, 41, 12, 66, 62],
       [92, 47, 66, 87, 35, 90, 76, 27,  9, 63]], dtype=int32)

In [79]:
arr1[0:6]

array([[67, 42, 57, 39, 89, 94, 92, 46, 48, 49],
       [71, 43, 36, 89, 92, 30, 75, 14, 77, 70],
       [68, 29, 90, 35, 28, 40, 58, 56, 45, 39],
       [ 1, 15, 63, 81,  9, 72, 96, 37, 86, 21],
       [60,  8, 26, 66, 95, 38, 92, 99, 67, 69],
       [62,  7, 71, 25, 70, 45, 89, 41, 17, 72]], dtype=int32)

In [81]:
arr1[1,6]

np.int32(75)

In [82]:
arr1[-6,-6]

np.int32(95)

In [83]:
arr1

array([[67, 42, 57, 39, 89, 94, 92, 46, 48, 49],
       [71, 43, 36, 89, 92, 30, 75, 14, 77, 70],
       [68, 29, 90, 35, 28, 40, 58, 56, 45, 39],
       [ 1, 15, 63, 81,  9, 72, 96, 37, 86, 21],
       [60,  8, 26, 66, 95, 38, 92, 99, 67, 69],
       [62,  7, 71, 25, 70, 45, 89, 41, 17, 72],
       [52, 53, 51, 11, 16,  6, 56, 73, 89,  6],
       [71, 43, 31, 64, 77, 28, 81, 60, 57, 57],
       [37, 96, 61, 31, 10, 56, 41, 12, 66, 62],
       [92, 47, 66, 87, 35, 90, 76, 27,  9, 63]], dtype=int32)

In [84]:
arr1[::-1]

array([[92, 47, 66, 87, 35, 90, 76, 27,  9, 63],
       [37, 96, 61, 31, 10, 56, 41, 12, 66, 62],
       [71, 43, 31, 64, 77, 28, 81, 60, 57, 57],
       [52, 53, 51, 11, 16,  6, 56, 73, 89,  6],
       [62,  7, 71, 25, 70, 45, 89, 41, 17, 72],
       [60,  8, 26, 66, 95, 38, 92, 99, 67, 69],
       [ 1, 15, 63, 81,  9, 72, 96, 37, 86, 21],
       [68, 29, 90, 35, 28, 40, 58, 56, 45, 39],
       [71, 43, 36, 89, 92, 30, 75, 14, 77, 70],
       [67, 42, 57, 39, 89, 94, 92, 46, 48, 49]], dtype=int32)

In [85]:
arr1[::-2]

array([[92, 47, 66, 87, 35, 90, 76, 27,  9, 63],
       [71, 43, 31, 64, 77, 28, 81, 60, 57, 57],
       [62,  7, 71, 25, 70, 45, 89, 41, 17, 72],
       [ 1, 15, 63, 81,  9, 72, 96, 37, 86, 21],
       [71, 43, 36, 89, 92, 30, 75, 14, 77, 70]], dtype=int32)

In [86]:
arr1[::-4]

array([[92, 47, 66, 87, 35, 90, 76, 27,  9, 63],
       [62,  7, 71, 25, 70, 45, 89, 41, 17, 72],
       [71, 43, 36, 89, 92, 30, 75, 14, 77, 70]], dtype=int32)

## max()
* it returns the largest value in the matrix
## min()
* it returns the minimum value in the matrix

In [87]:
arr1.max()

np.int32(99)

In [88]:
arr1.min()

np.int32(1)

In [89]:
arr

array([0, 1, 2, 3, 4, 5])

## median()
* it gives the middile value in a matrix if the matrix is in odd no
* if the matrix is even then it will add  the 2 middle no the divide it by 2
## mean()
* it gives the average no in the matrix

In [90]:
arr.median()

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [94]:
from numpy import *
a=arr
median(a)

np.float64(2.5)

In [95]:
arr1.mean()

np.float64(53.54)

In [96]:
median(arr1)

np.float64(56.5)

In [97]:
arr

array([0, 1, 2, 3, 4, 5])

In [98]:
arr.reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [99]:
arr.reshape(2,3,order='c') # hy

array([[0, 1, 2],
       [3, 4, 5]])

In [101]:
arr.reshape(2,3,order='F')# print element with fortran 

array([[0, 2, 4],
       [1, 3, 5]])

In [102]:
arr.reshape(2,3,order='A') # A almost give you c type output 

array([[0, 1, 2],
       [3, 4, 5]])

## indexing

In [103]:
mat = np.arange(0,100).reshape(10,10)

In [104]:
mat


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [105]:
row=4
col=7

In [106]:
mat[row,col]

np.int64(47)

In [107]:
mat[:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [108]:
mat[6]

array([60, 61, 62, 63, 64, 65, 66, 67, 68, 69])

In [110]:
mat[:,col]

array([ 7, 17, 27, 37, 47, 57, 67, 77, 87, 97])

In [111]:
mat[row,:]

array([40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [112]:
mat[:,7]

array([ 7, 17, 27, 37, 47, 57, 67, 77, 87, 97])

In [113]:
mat[:col]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69]])

In [114]:
mat[:,-1]

array([ 9, 19, 29, 39, 49, 59, 69, 79, 89, 99])

In [115]:
mat[3,-3]

np.int64(37)

In [116]:
mat[3:-3]

array([[30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69]])

In [117]:
mat


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [118]:
mat[5]

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59])

In [119]:
mat[5:]

array([[50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [120]:
mat[:5]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [121]:
mat[0: :3]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [122]:
mat[::-5]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [123]:
mat[2:6,5:7]#2:6 is only row part and 5:7 is only column part

array([[25, 26],
       [35, 36],
       [45, 46],
       [55, 56]])

In [124]:
mat[2:3,2:3] 

array([[22]])

## masking

In [125]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [126]:
mat< 50

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [128]:
mat[mat<50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [129]:
mat[mat>50]

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [130]:
mat[mat==50]

array([50])

In [131]:
mat[mat!=50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

# TASK2

## 1. Array Creation Functions

In [133]:
import numpy as np

In [134]:
b=np.array([1,2,3])
print(b)

[1 2 3]


In [136]:
c = np.arange(0, 10, 2)  # Values from 0 to 10 with step 2
print("Array b:", c)

Array b: [0 2 4 6 8]


### linespace()
* Return evenly spaced numbers over a specified interval


In [137]:
n=np.linspace(0,1,5)
print(n)

[0.   0.25 0.5  0.75 1.  ]


In [140]:
o=np.ones(11)
o

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [141]:
o_=np.ones([11,10])
o_

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

### ones()
*Return a 2-D array with ones on the diagonal and zeros elsewhere.

In [145]:
e=np.eye(4)
e

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## 2. Array Manipulation Functions

In [149]:
# Reshape an array
a1=np.arange(1,7)
print(a1)
a2=np.reshape(a1,(2,3))
print(a2)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


### ravel()
* a 1-D array, containing the elements of the input, is returned.  A copy is
made only if needed.

In [148]:
# Flatten an array
f1=np.array([[1,2],[3,4]])
flattenend=np.ravel(f1)# Flatten to 1D array
print(flattenend)

[1 2 3 4]


### transpose()
* Returns an array with axes transposed.

In [152]:
t=np.arange(0,12).reshape(3,4)
print(t)
t1=np.transpose(t)
print(t1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


### vstack()
* Stack arrays in sequence vertically (row wise).

In [153]:
 #Stack arrays vertically
a2 = np.array([1, 2])
b2 = np.array([3, 4])
stacked = np.vstack([a2, b2])  # Stack a and b vertically
print("Stacked arrays:\n", stacked)

Stacked arrays:
 [[1 2]
 [3 4]]


## 3. Mathematical Functions

### add()
* used to add 2 different array
### power()
* used to fing square of an array
### sqrt()
* used to find squre root of an array
### dot()
* Dot product of two arrays. Specifically,

In [154]:
g=np.array([1,2,3,4])
result=np.add(g,2)
print(result)

[3 4 5 6]


In [157]:
sqr=np.power(g,2)
sqr

array([ 1,  4,  9, 16])

In [161]:
root=np.array([ 1,  4,  9, 16])
print(root)
root2=np.sqrt(root)
print(root2)

[ 1  4  9 16]
[1. 2. 3. 4.]


In [163]:
a
a2

array([1, 2])

In [169]:
a3=np.array([1,2])
ans=np.dot(a2,a3)
print(ans)

5


## 4. Statistical Functions

In [170]:
s=np.array([1,2,3,4])
meann=np.mean(s)
print(meann)

2.5


In [172]:
# standard deviation of array
st_dev=np.std(s)
print(st_dev)

1.118033988749895


In [173]:
minimum=s.min()
print(minimum)

1


In [175]:
maaximum=max(s)
print(maaximum)

4


## 5. Linear Algebra Functions
### linalg.det()
* Compute the determinant of an array.
### linalg.inv() 
+ Compute the inverse of a matrix.

In [176]:
matrix= np.array([[1, 2], [3, 4]])

In [177]:
determinant = np.linalg.det(matrix)
print("Determinant of matrix:", determinant)

Determinant of matrix: -2.0000000000000004


In [178]:
inverse = np.linalg.inv(matrix)
print("Inverse of matrix:\n", inverse)# Inverse of a matrix

Inverse of matrix:
 [[-2.   1. ]
 [ 1.5 -0.5]]


## 6. Random Sampling Functions

In [180]:
rval=np.random.rand(3)
print(rval)

[0.34723531 0.55977532 0.95865647]


In [185]:
np.random.seed(1)
rval=np.random.rand(3)
print(rval)

[4.17022005e-01 7.20324493e-01 1.14374817e-04]


In [187]:
rval_int=np.random.randint(0,6,5)
print(rval_int)

[3 5 0 0 1]


In [188]:
# Set seed for reproducibility
np.random.seed(0)

# Generate random integers
rand_ints = np.random.randint(0, 10, size=5)  # Random integers between 0 and 10
print("Random integers:", rand_ints)

Random integers: [5 0 3 3 7]


## 7. Boolean & Logical Functions

In [190]:
logi = np.array([True, False, True])

In [193]:
all_true=np.all(logi)
print(all_true)

False


In [194]:
logi2=np.array([True, True, True])

In [195]:
all_true2=np.all(logi2)
print(all_true2)

True


In [196]:
any_true=np.any(logi)
print(any_true)

True


In [197]:
any_true2=np.any(logi2)
print(any_true)

True


## 8. Set Operations

In [198]:
# Intersection of two arrays
set1 = np.array([1, 2, 3, 4])
set2 = np.array([3, 7, 5, 6])
intersection = np.intersect1d(set1, set2)
print("Intersection of a and b:", intersection)

Intersection of a and b: [3]


In [200]:
set1 = np.array([1, 2, 3, 4])
set2 = np.array([3, 7, 5, 6])
unionid = np.union1d(set1, set2)
print("union of a and b:", unionid)

union of a and b: [1 2 3 4 5 6 7]


## 9. Array Attribute Functions

In [201]:
a

array([0, 1, 2, 3, 4, 5])

In [204]:
shp=a.shape
print(shp)
size=a.size
print(size)
dimension=a.ndim
print(dimension)
dtype=a.dtype
print(dtype)

(6,)
6
1
int64


## 10. Other Functions

In [205]:
a

array([0, 1, 2, 3, 4, 5])

In [206]:
copy_of_a=np.copy(a)
print(copy_of_a)

[0 1 2 3 4 5]


In [207]:
# Size in bytes of an array
array_size_in_bytes = a.nbytes  # Size in bytes
print("Size of a in bytes:", array_size_in_bytes)

Size of a in bytes: 48


In [208]:
# Check if two arrays share memory
shared = np.shares_memory(a, copy_of_a)  # Check if arrays share memory
print("Do a and copied_array share memory?", shared)

Do a and copied_array share memory? False
